version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    links:
      - mysql
    networks:
      - app-tier
    ports:
      - "127.0.0.1:82:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./:/var/www/
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      - app-tier
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: bushe
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: bushe
      MYSQL_PASSWORD: root
    volumes:
      - ./docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.1
    container_name: phpmyadmin
    restart: always
    networks:
      - app-tier
    ports:
      - "127.0.0.1:89:80"
    environment:
      PMA_HOST: mysql




